name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include: [
          { sanitizer: 1, buildtype: Debug },
          { sanitizer: 0, buildtype: Release },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.6
        env:
          CC: clang
          CXX: clang++
        with:
          envs: 'CC CXX'
          prepare: |
            pkg install -y cmake gmake
          run: |
            cmake -S . -B build \
              -DBUILD_TESTING=ON \
              -DENABLE_WARNINGS=ON \
              -DENABLE_SANITIZE=${{matrix.sanitizer}} \
              -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
            cmake --build build
            cmake --build build --target test
