name: macos
on:
  workflow_dispatch:
jobs:
  MacOS:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { sanitizer: 1, buildtype: Debug },
          { sanitizer: 0, buildtype: Release },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Run cmake
        run: |
          set -x
          cmake -S . -B build \
            -DBUILD_TESTING=ON \
            -DENABLE_WARNINGS=ON \
            -DENABLE_SANITIZE=${{matrix.sanitizer}} \
            -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
          cmake --build build
      - name: Run ctest
        run: |
          set -x
          cmake --build build --target test
